---
stages:
  - build
  - test
  - package
  - package-test
  - deploy
  - deploy-test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

image: gwdiexp/lpsd:develop

compile:
  stage: build
  script:
    - make compile
  artifacts:
    paths:
      - lpsd/*.so
    expire_in: 1 week

package:
  stage: package
  script:
    - make package
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  needs: [compile]

test:
  stage: test
  script:
    - make test
  artifacts:
    paths:
      - htmlcov
    expire_in: 30 days
  needs: [compile]

mypy:
  stage: test
  script:
    - make mypy
  needs: []

pylint:
  stage: test
  script:
    - make pylint
  needs: []

black:
  stage: test
  script:
    - black --check lpsd test
  needs: []

deploy production:
  stage: deploy
  script:
    # Official PyPi server
    - poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
    - poetry publish
  only:
    - tags

test wheel installation:
  image: python:3.10
  stage: package-test
  script:
    - pip3 install `ls dist/*.whl`
    - python3 -c "import lpsd; print(openqlab.__path__)"
    - python3 -c "import lpsd; print(openqlab.__version__)"
    - python3 -c "from lpsd import lpsd"
  cache:
    key: lpsd:pip
    paths:
      - .pip/
  needs:
    - [package]
  only:
    - develop
    - main
    - tags
